environment           = "dev"
region                = "ap-southeast-1"
tf_state_bucket       = "test-s3-idlmreplatforming-tfstate"
log_group_tag_name    = "dev-DockerAPI"
ssm_param_name        = "/cloudwatch/docker-config"
docker_log_group_name = "/dev/docker/api"
ssm_tag_name          = "docker-cloudwatch-config"
tf_state_region       = "ap-southeast-1"